/** Long backbone phrases for endless mode (mirrors endlessBackbone.json). */
export const ENDLESS_BACKBONE_CHAINS = [
  ["light", "house", "party", "time", "card", "game", "night", "shift", "manager", "meeting", "room", "temperature", "check", "engine", "light", "switch", "case", "study", "group", "chat", "message", "board", "game", "plan", "review", "board", "member", "profile", "picture", "frame"],
  ["water", "bottle", "cap", "space", "heater", "control", "panel", "board", "game", "night", "club", "house", "plant", "food", "chain", "reaction", "time", "card", "game", "plan", "ahead", "schedule", "meeting", "room", "service", "desk", "job", "title", "track", "record"],
  ["fire", "alarm", "system", "error", "message", "board", "member", "profile", "picture", "frame", "rate", "limit", "order", "form", "fill", "page", "turn", "signal", "light", "switch", "case", "study", "guide", "book", "club", "house", "party", "game", "night", "shift"],
  ["sun", "light", "bulb", "socket", "wrench", "tool", "box", "office", "chair", "lift", "system", "error", "code", "review", "board", "game", "plan", "ahead", "schedule", "time", "card", "game", "night", "shift", "work", "force", "field", "day", "care", "center"],
  ["rain", "coat", "pocket", "watch", "band", "camp", "fire", "pit", "stop", "sign", "language", "barrier", "reef", "fish", "tank", "top", "shelf", "life", "hack", "job", "site", "map", "key", "chain", "link", "building", "block", "party", "game", "night"],
  ["power", "line", "drive", "way", "back", "yard", "sale", "price", "tag", "team", "leader", "board", "game", "night", "shift", "manager", "role", "model", "train", "track", "record", "deal", "breaker", "point", "guard", "rail", "road", "trip", "plan", "review"],
  ["gold", "mine", "field", "day", "care", "center", "stage", "light", "switch", "case", "study", "group", "project", "plan", "review", "board", "member", "profile", "picture", "frame", "rate", "cut", "tool", "box", "office", "desk", "job", "title", "track", "record"],
  ["ice", "cream", "cone", "head", "coach", "team", "leader", "board", "game", "night", "club", "house", "party", "favor", "bag", "pack", "leader", "role", "model", "train", "track", "record", "deal", "breaker", "point", "guard", "rail", "road", "trip"],
  ["fast", "lane", "change", "gear", "shift", "knob", "control", "panel", "board", "game", "night", "shift", "manager", "meeting", "room", "service", "desk", "job", "title", "track", "record", "deal", "breaker", "point", "guard", "rail", "road", "map", "key"],
  ["deep", "sleep", "cycle", "time", "card", "game", "night", "shift", "manager", "role", "model", "train", "track", "record", "deal", "breaker", "point", "guard", "rail", "road", "trip", "plan", "review", "board", "member", "profile", "picture", "frame", "rate", "cut"],
];
