import { ENDLESS_BACKBONE_CHAINS } from "./endlessBackboneChains.js";

// Each adjacent pair should form a common phrase.
// Standard mode chains are 5 words long (see DIFFICULTY.chainLen in app.js).
export const WORD_CHAINS = [
  ["apple", "pie", "crust", "pizza", "delivery"],
  ["credit", "card", "balance", "transfer", "service"],
  ["phone", "call", "center", "stage", "light"],
  ["movie", "theater", "room", "temperature", "check"],
  ["coffee", "shop", "owner", "manual", "labor"],
  ["game", "night", "shift", "manager", "meeting"],
  ["car", "seat", "belt", "loop", "band"],
  ["desk", "job", "title", "track", "record"],
  ["water", "bottle", "cap", "space", "heater"],
  ["music", "video", "game", "plan", "ahead"],
  ["book", "club", "member", "profile", "picture"],
  ["hair", "brush", "stroke", "play", "action"],
  ["door", "bell", "ring", "tone", "control"],
  ["road", "trip", "plan", "review", "board"],
  ["sun", "light", "bulb", "socket", "wrench"],
  ["rain", "coat", "pocket", "watch", "band"],
  ["fire", "alarm", "system", "error", "message"],
  ["snow", "ball", "fight", "club", "house"],
  ["mail", "box", "office", "chair", "lift"],
  ["shoe", "lace", "pattern", "match", "point"],
  ["table", "cloth", "napkin", "holder", "stand"],
  ["window", "frame", "rate", "limit", "order"],
  ["clock", "tower", "bridge", "loan", "payment"],
  ["heart", "rate", "monitor", "screen", "time"],
  ["brain", "storm", "drain", "clean", "room"],
  ["tree", "house", "plant", "food", "chain"],
  ["bed", "room", "light", "switch", "case"],
  ["air", "plane", "mode", "control", "panel"],
  ["note", "book", "page", "turn", "signal"],
  ["paper", "cut", "scene", "partner", "deal"],
  ["field", "goal", "line", "drive", "test"],
  ["back", "pack", "strap", "handle", "bar"],
  ["hand", "bag", "collection", "item", "shop"],
  ["eye", "contact", "lens", "case", "study"],
  ["lip", "stick", "shade", "color", "palette"],
  ["tooth", "brush", "holder", "phone", "case"],
  ["glass", "door", "handle", "grip", "strength"],
  ["rock", "band", "tour", "bus", "driver"],
  ["farm", "land", "owner", "manual", "guide"],
  ["ship", "deck", "chair", "lift", "system"],
  ["wheel", "chair", "access", "code", "entry"],
  ["ink", "pen", "tip", "line", "graph"],
  ["bed", "frame", "rate", "cut", "tool"],
  ["door", "frame", "work", "life", "balance"],
  ["road", "map", "key", "chain", "link"],
  ["time", "card", "game", "night", "club"],
  ["job", "site", "manager", "role", "model"],
  ["team", "leader", "board", "game", "store"],
  ["price", "tag", "label", "maker", "tool"],
  ["work", "force", "field", "day", "care"],
];
/** Extra chains that share words to build a larger phrase graph for Endless mode. */
export const EXTENDED_PHRASE_CHAINS = [
  ["apple", "pie", "plate", "glass", "cut", "back"],
  ["silver", "bullet", "point", "blank", "check", "list"],
  ["honey", "bee", "hive", "mind", "game", "plan"],
  ["golden", "gate", "bridge", "club", "house", "key"],
  ["baby", "boom", "town", "hall", "mark", "down"],
  ["ice", "cream", "soda", "shop", "lift", "off"],
  ["hot", "dog", "fight", "club", "sandwich", "board"],
  ["birth", "day", "dream", "land", "slide", "show"],
  ["sand", "storm", "front", "page", "view", "point"],
  ["bread", "winner", "circle", "back", "track", "list"],
  ["spring", "roll", "play", "house", "cat", "walk"],
  ["basket", "case", "study", "group", "work", "shop"],
  ["chicken", "wing", "man", "hole", "cover", "girl"],
  ["pocket", "change", "heart", "burn", "rate", "cut"],
  ["finger", "nail", "file", "folder", "paper", "jam"],
  ["shadow", "play", "wright", "house", "boat", "load"],
  ["trade", "wind", "fall", "leaf", "blower", "door"],
  ["back", "pack", "rat", "race", "horse", "shoe"],
  ["court", "ship", "yard", "arm", "chair", "lift"],
  ["post", "card", "board", "room", "mate", "rate"],
  ["road", "runner", "bean", "bag", "pipe", "line"],
  ["tree", "line", "back", "fire", "wall", "paper"],
  ["bird", "house", "boat", "yard", "stick", "pin"],
  ["flower", "child", "hood", "wink", "rate", "cut"],
  ["pipe", "organ", "bank", "roll", "call", "back"],
  ["dream", "coat", "rack", "city", "bus", "lane"],
  ["brain", "wash", "cloth", "drying", "rack", "room"],
  ["storm", "water", "fall", "off", "ramp", "art"],
  ["game", "face", "book", "worm", "hole", "shot"],
  ["door", "step", "child", "proof", "read", "out"],
  ["room", "fair", "play", "boy", "band", "aid"],
  ["light", "house", "boat", "load", "stone", "wall"],
  ["coat", "room", "rate", "pay", "back", "spin"],
  ["mail", "slot", "machine", "gun", "fire", "arm"],
  ["fire", "iron", "side", "walk", "way", "out"],
  ["water", "cooler", "head", "stone", "wall", "nut"],
  ["sun", "roof", "rack", "room", "key", "board"],
  ["snow", "plow", "man", "hole", "punch", "bowl"],
  ["paper", "trail", "mix", "match", "box", "seat"],
  ["cell", "mate", "ship", "shape", "shift", "work"],
];

/** All chains used to construct the phrase adjacency graph. */
export const ALL_PHRASE_CHAINS = [...WORD_CHAINS, ...EXTENDED_PHRASE_CHAINS, ...ENDLESS_BACKBONE_CHAINS];
